INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION)
VALUES
(SEQ_DEPT_ID.NEXTVAL, 'Management', 'London');

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION)
VALUES
(SEQ_DEPT_ID.NEXTVAL, 'Engineering', 'Cardiff');

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION)
VALUES
(SEQ_DEPT_ID.NEXTVAL, 'Research '||'&'||' Development', 'Edinburgh');

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION)
VALUES
(SEQ_DEPT_ID.NEXTVAL, 'Sales', 'Belfast');


COMMIT;
